jackal_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

jackal_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.5 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0   # rad/s^2

ekf_localization:
  frequency: 50
  odom0: /jackal_velocity_controller/odom
  odom0_config: [true, true, false,
                 false, false, false,
                 true, true, true,
                 false, false, true]
  odom0_differential: true
  imu0: /imu/data
  imu0_config: [false, false, false,
                true, true, true,
                false, false, false,
                true, true, true]
  imu0_differential: false
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

# Custom Navigation Stack-based controller
reelrbtx_follow_controller:
   type: reelrbtx_follow_controller/ReelRbtxFollowController
   joint: reel_wheel
   state_publish_rate: 100 # hz
   cycle_hz: 200
   av_ratio: 1
   cmd_vel_topic: /jackal_velocity_controller/cmd_vel

# Individual Position Controllers
# Allows to send individual ROS msg of Float64 to each joint separately
reelrbtx_joint_position_controller:
   type: position_controllers/JointPositionController
   joint: reel_wheel
   pid: {p: 100.0, i: 0.01, d: 10.0}
